apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-rangulo
  labels:
    app: mi-app-rangulo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-app-rangulo
  template:
    metadata:
      labels:
        app: mi-app-rangulo
    spec:
      containers:
        - name: mi-app-rangulo
          image: rangulo1972/jenkins-node:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mi-app-rangulo-service
spec:
  selector:
    app: mi-app-rangulo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer