name: Flujo de trabajo para validar cache en actions

on: 
  push:
    branches:
      - codigo

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Guardar en cache npm install...
        id: cache-npm-packages
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-dependencies

      - name: Instalar dependencias...
        run: npm install
      
  test-cache:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Restaurar dependencias de npm
        uses: actions/cache/restore@v4
        id: cache-npm-packages
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-dependencies

      - name: Reinstall npm project packages
        run: npm i

      - name: Ejecutar mis tests..
        run: npm run test